version: '3'
services:
  mongodb:
    image: bitnami/mongodb
    restart: always
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=project1-db
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'